### ISSUE TITLE
Style enhancements

### ISSUE THREAD

**Issue by ManarArabi** [Eyadhamza/Eng-Hammad-Recommendations#3]
## Description
I think if the links embedded into the text, it will have better readability .. I updated it in a branch already but couldn't push the branch to create a PR.

![Screenshot from 2021-04-27 19-30-58](https://user-images.githubusercontent.com/31085651/116286117-25b96100-a78f-11eb-8cb6-a70bda807b58.png)

**Comment by mohamedSabry0** [comment]
maybe you can do so on a forked repo instead of the original, then make a pull request to merge into the original.
you are trying to push the branch directly to the original one right? instead, you can:
- fork the original
- create the branch on the forked one
- push it to the forked
- create a pull request on the forked with the branch from the original as a base

I hope this was helpful

**Comment by ManarArabi** [comment]
> maybe you can do so on a forked repo instead of the original, then make a pull request to merge into the original.
> you are trying to push the branch directly to the original one right? instead, you can:
> 
> * fork the original
> * create the branch on the forked one
> * push it to the forked
> * create a pull request on the forked with the branch from the original as a base
> 
> I hope this was helpful

Thank You .. I'll do so.

**Comment by Eyadhamza** [comment]
@ManarArabi 
The styles now has been applied, thanks a lot for pointing this out
And of course thanks to @Fighteros for the PR :)
